import Mcmc.Hamiltonian.Discontinuous
import Mcmc.Finite.MetropolisHastings
import Mcmc.Finite.MarkovKernel
import Mathlib.Probability.Distributions.Exponential
import Mathlib.MeasureTheory.Measure.Real

/-!
# One-step discontinuous HMC as Metropolis

For a positive finite target and a positive symmetric coordinate proposal,
this module identifies the probability that refreshed Laplace kinetic energy
crosses the negative-log target jump with the ordinary Metropolis--Hastings
acceptance probability.  This is the checked `L = 1` bridge described by
Nishimura, Dunson, and Lu; repeated coordinate trajectories require the
separate distributional-reversibility argument.
-/

namespace Mcmc.Hamiltonian

open MeasureTheory ProbabilityTheory Set
open Mcmc.Finite
open Mcmc.Finite.MarkovKernel

variable {State : Type*} [Fintype State] [DecidableEq State]

/-- A finite coordinate proposal whose two directions have the same positive
probability.  This is the discrete proposal generated by refreshing the sign
of one Laplace momentum coordinate. -/
structure DiscontinuousCoordinateProposal (State : Type*) [Fintype State]
    where
  kernel : MarkovKernel State
  symmetric : ∀ x y, kernel.prob x y = kernel.prob y x
  positive : ∀ x y, 0 < kernel.prob x y

omit [DecidableEq State] in
/-- A positive symmetric proposal cancels out of the Hastings ratio. -/
theorem symmetric_positive_acceptance_eq_target_ratio
    (target : Distribution State) (proposal : MarkovKernel State)
    {current candidate : State}
    (htarget : ∀ x, 0 < target.mass x)
    (hsymm : proposal.prob current candidate =
      proposal.prob candidate current)
    (hproposal : 0 < proposal.prob current candidate) :
    MetropolisHastings.acceptance target proposal current candidate =
      min 1 (target.mass candidate / target.mass current) := by
  unfold MetropolisHastings.acceptance
  rw [← hsymm]
  congr 1
  field_simp [ne_of_gt (htarget current), ne_of_gt hproposal]

omit [DecidableEq State] in
/-- The refreshed-Laplace crossing event has exactly the MH acceptance
probability for a positive symmetric coordinate proposal. -/
theorem expMeasure_crossing_probability_eq_mh_acceptance
    (target : Distribution State) (proposal : MarkovKernel State)
    {current candidate : State}
    (htarget : ∀ x, 0 < target.mass x)
    (hsymm : proposal.prob current candidate =
      proposal.prob candidate current)
    (hproposal : 0 < proposal.prob current candidate) :
    (expMeasure 1).real
        (Ioi (Real.log (target.mass current) -
          Real.log (target.mass candidate))) =
      MetropolisHastings.acceptance target proposal current candidate := by
  rw [Mcmc.Hamiltonian.expMeasure_logWeight_crossing_probability
      (htarget current) (htarget candidate),
    symmetric_positive_acceptance_eq_target_ratio target proposal htarget
      hsymm hproposal]

/-- The finite one-update discontinuous-HMC position kernel.  The preceding
crossing theorem identifies its acceptance coin with refreshed Laplace
kinetic energy, rather than postulating an unrelated Metropolis coin. -/
noncomputable def oneStepDiscontinuousKernel
    (target : Distribution State) (proposal : DiscontinuousCoordinateProposal State)
    (htarget : ∀ x, 0 < target.mass x) : MarkovKernel State :=
  MetropolisHastings.kernel target proposal.kernel htarget

/-- One-step finite discontinuous HMC preserves its positive target. -/
theorem oneStepDiscontinuousKernel_stationary
    (target : Distribution State) (proposal : DiscontinuousCoordinateProposal State)
    (htarget : ∀ x, 0 < target.mass x) :
    (oneStepDiscontinuousKernel target proposal htarget).Stationary target :=
  MetropolisHastings.stationary target proposal.kernel htarget

omit [DecidableEq State] in
/-- Every proposed edge in the finite one-step kernel uses exactly the
refreshed-Laplace crossing probability. -/
theorem oneStepDiscontinuousKernel_acceptance_eq_crossing
    (target : Distribution State) (proposal : DiscontinuousCoordinateProposal State)
    (htarget : ∀ x, 0 < target.mass x) (current candidate : State) :
    MetropolisHastings.acceptance target proposal.kernel current candidate =
      (expMeasure 1).real
        (Ioi (Real.log (target.mass current) -
          Real.log (target.mass candidate))) := by
  symm
  exact expMeasure_crossing_probability_eq_mh_acceptance target proposal.kernel
    htarget (proposal.symmetric current candidate)
      (proposal.positive current candidate)

end Mcmc.Hamiltonian
