/-! Deterministic emitter for the finite Julia reference core. -/

private def generatedSource : String := r#"# This file is generated by `lake exe generate_julia`; do not edit.

module FiniteCore

using ...Runtime: AbstractRandomSource, draw_below!

function categorical_index!(source::AbstractRandomSource, weights::AbstractVector{<:Integer})
    all(weight -> weight >= 0, weights) || throw(ArgumentError("weights must be nonnegative"))
    total = sum(big, weights)
    total > 0 || throw(ArgumentError("weights must have positive total"))
    draw = draw_below!(source, total)
    for (index, weight) in pairs(weights)
        draw < weight && return index - 1
        draw -= weight
    end
    error("draw_below! violated its range contract")
end

function two_state_mh_step!(source::AbstractRandomSource, current::Integer)
    0 <= current < 2 || throw(ArgumentError("state must be 0 or 1"))
    proposed = categorical_index!(source, BigInt[1, 1])
    proposed == current && return current
    upper = current == 0 ? big(2) : big(6)
    threshold = big(2)
    draw_below!(source, upper) < threshold ? proposed : current
end

end
"#

def main (args : List String) : IO UInt32 := do
  match args with
  | [path] =>
      IO.FS.writeFile path generatedSource
      return 0
  | _ =>
      IO.eprintln "usage: generate_julia OUTPUT"
      return 2
