/-! Deterministic emitter for the finite Julia reference core. -/

private def generatedSource : String := r#"# This file is generated by `lake exe generate_julia`; do not edit.

module FiniteCore

using ...Runtime: AbstractRandomSource, draw_below!

function categorical_index!(source::AbstractRandomSource, weights::AbstractVector{<:Integer})
    all(weight -> weight >= 0, weights) || throw(ArgumentError("weights must be nonnegative"))
    total = sum(big, weights)
    total > 0 || throw(ArgumentError("weights must have positive total"))
    draw = draw_below!(source, total)
    for (index, weight) in pairs(weights)
        draw < weight && return index - 1
        draw -= weight
    end
    error("draw_below! violated its range contract")
end

function two_state_mh_step!(source::AbstractRandomSource, current::Integer)
    finite_mh_step!(source, BigInt[1, 3], [BigInt[1, 1], BigInt[1, 1]], current)
end

function finite_mh_step!(source::AbstractRandomSource,
        target::AbstractVector{<:Integer}, proposal::AbstractVector, current::Integer)
    target_weights = BigInt.(target)
    all(weight -> weight > 0, target_weights) ||
        throw(ArgumentError("target weights must be positive"))
    state_count = length(target_weights)
    length(proposal) == state_count || throw(DimensionMismatch("proposal row count"))
    0 <= current < state_count || throw(ArgumentError("current state is out of range"))
    rows = [BigInt.(row) for row in proposal]
    all(row -> length(row) == state_count, rows) ||
        throw(DimensionMismatch("proposal column count"))
    all(row -> all(weight -> weight >= 0, row) && sum(row) > 0, rows) ||
        throw(ArgumentError("proposal rows need nonnegative weights and positive totals"))

    proposed = categorical_index!(source, rows[current + 1])
    proposed == current && return current
    current_total = sum(rows[current + 1])
    proposed_total = sum(rows[proposed + 1])
    forward = rows[current + 1][proposed + 1]
    reverse = rows[proposed + 1][current + 1]
    upper = target_weights[current + 1] * forward * proposed_total
    threshold = min(upper,
        target_weights[proposed + 1] * reverse * current_total)
    draw_below!(source, upper) < threshold ? proposed : current
end

end
"#

def main (args : List String) : IO UInt32 := do
  match args with
  | [path] =>
      IO.FS.writeFile path generatedSource
      return 0
  | _ =>
      IO.eprintln "usage: generate_julia OUTPUT"
      return 2
