import Mcmc.Finite.GreedyTransport
import Mcmc.Finite.TransportPolytope

/-!
# Completeness of greedy finite transport candidates

This module develops the forest-to-greedy half of the finite transport
selector proof.  A leaf-elimination order removes an edge whose remaining row
or remaining column contains no other positive target mass.  The first lemmas
show that greedy allocation at such an edge is exactly its target mass.
-/

open scoped BigOperators ENNReal

namespace Mcmc.Finite

variable {α β : Type*} [DecidableEq α] [DecidableEq β]

/-- A finite forest containing an edge has a leaf vertex.  Mathlib provides
the result for nontrivial trees; restricting to the connected component of a
given edge yields this forest form. -/
theorem SimpleGraph.IsAcyclic.exists_degree_one_of_adj
    {V : Type*} [Fintype V] {G : SimpleGraph V} [DecidableRel G.Adj]
    (hacyclic : G.IsAcyclic) {u w : V} (huw : G.Adj u w) :
    ∃ v, G.degree v = 1 := by
  classical
  let component := G.connectedComponentMk u
  have hu : u ∈ component := SimpleGraph.ConnectedComponent.connectedComponentMk_mem
  have hw : w ∈ component :=
    (component.mem_supp_congr_adj huw).mp hu
  let u' : component := ⟨u, hu⟩
  let w' : component := ⟨w, hw⟩
  have huwne : u' ≠ w' := by
    intro h
    have : u = w := congrArg Subtype.val h
    subst w
    exact G.loopless.irrefl u huw
  letI : Nontrivial component := ⟨⟨u', w', huwne⟩⟩
  letI : DecidableRel component.toSimpleGraph.Adj := Classical.decRel _
  obtain ⟨v, hv⟩ :=
    (hacyclic.isTree_connectedComponent component).exists_vert_degree_one_of_nontrivial
  obtain ⟨neighbor, hvneighbor, hunique⟩ :=
    SimpleGraph.degree_eq_one_iff_existsUnique_adj.mp hv
  refine ⟨v.1, SimpleGraph.degree_eq_one_iff_existsUnique_adj.mpr
    ⟨neighbor.1, ?_, ?_⟩⟩
  · exact (component.toSimpleGraph_adj v.2 neighbor.2).mp hvneighbor
  · intro candidate hvcandidate
    have hcandidate : candidate ∈ component :=
      (component.mem_supp_congr_adj hvcandidate).mp v.2
    have hadjComponent : component.toSimpleGraph.Adj v ⟨candidate, hcandidate⟩ :=
      (component.toSimpleGraph_adj v.2 hcandidate).mpr hvcandidate
    exact congrArg Subtype.val (hunique ⟨candidate, hcandidate⟩ hadjComponent)

/-- Bipartite graph generated by a finite set of transport-table edges. -/
def transportEdgeGraph (edges : Finset (α × β)) : SimpleGraph (α ⊕ β) where
  Adj u v :=
    match u, v with
    | .inl i, .inr j => (i, j) ∈ edges
    | .inr j, .inl i => (i, j) ∈ edges
    | .inl _, .inl _ | .inr _, .inr _ => False
  symm := ⟨by
    intro u v huv
    cases u <;> cases v <;> exact huv⟩
  loopless := ⟨by
    intro u huu
    cases u <;> exact huu⟩

omit [DecidableEq α] [DecidableEq β] in
@[simp]
theorem transportEdgeGraph_adj_inl_inr
    (edges : Finset (α × β)) (i : α) (j : β) :
    (transportEdgeGraph edges).Adj (.inl i) (.inr j) ↔ (i, j) ∈ edges :=
  Iff.rfl

omit [DecidableEq α] [DecidableEq β] in
@[simp]
theorem transportEdgeGraph_adj_inr_inl
    (edges : Finset (α × β)) (j : β) (i : α) :
    (transportEdgeGraph edges).Adj (.inr j) (.inl i) ↔ (i, j) ∈ edges :=
  Iff.rfl

omit [DecidableEq α] [DecidableEq β] in
/-- Removing table edges produces a spanning subgraph. -/
theorem transportEdgeGraph_mono {smaller larger : Finset (α × β)}
    (h : smaller ⊆ larger) :
    transportEdgeGraph smaller ≤ transportEdgeGraph larger := by
  intro u v huv
  cases u <;> cases v
  · exact huv.elim
  · exact h huv
  · exact h huv
  · exact huv.elim

/-- An edge is combinatorially a leaf in a remaining edge finset when no
other edge in that finset meets one of its endpoints. -/
def IsTransportEdgeFinsetLeaf (edge : α × β)
    (remaining : Finset (α × β)) : Prop :=
  (∀ j, (edge.1, j) ∉ remaining) ∨
    ∀ i, (i, edge.2) ∉ remaining

/-- Every nonempty finite acyclic transport-edge graph has an edge that is a
leaf after that edge itself is removed. -/
theorem exists_mem_isTransportEdgeFinsetLeaf
    [Fintype α] [Fintype β] (edges : Finset (α × β))
    (hnonempty : edges.Nonempty)
    (hacyclic : (transportEdgeGraph edges).IsAcyclic) :
    ∃ edge ∈ edges,
      IsTransportEdgeFinsetLeaf edge (edges.erase edge) := by
  classical
  obtain ⟨initial, hinitial⟩ := hnonempty
  have hadjInitial : (transportEdgeGraph edges).Adj
      (.inl initial.1) (.inr initial.2) := hinitial
  obtain ⟨vertex, hdegree⟩ :=
    Mcmc.Finite.SimpleGraph.IsAcyclic.exists_degree_one_of_adj
      hacyclic hadjInitial
  obtain ⟨neighbor, hadj, hunique⟩ :=
    SimpleGraph.degree_eq_one_iff_existsUnique_adj.mp hdegree
  cases vertex with
  | inl i =>
      cases neighbor with
      | inl i' => exact hadj.elim
      | inr j =>
          have hedge : (i, j) ∈ edges := hadj
          refine ⟨(i, j), hedge, Or.inl ?_⟩
          intro j' hj'
          have hadj' : (transportEdgeGraph edges).Adj (.inl i) (.inr j') :=
            (Finset.mem_erase.mp hj').2
          have heq : (Sum.inr j' : α ⊕ β) = Sum.inr j :=
            hunique (.inr j') hadj'
          have hjEq : j' = j := Sum.inr.inj heq
          subst j'
          exact (Finset.mem_erase.mp hj').1 rfl
  | inr j =>
      cases neighbor with
      | inl i =>
          have hedge : (i, j) ∈ edges := hadj
          refine ⟨(i, j), hedge, Or.inr ?_⟩
          intro i' hi'
          have hadj' : (transportEdgeGraph edges).Adj (.inr j) (.inl i') :=
            (Finset.mem_erase.mp hi').2
          have heq : (Sum.inl i' : α ⊕ β) = Sum.inl i :=
            hunique (.inl i') hadj'
          have hiEq : i' = i := Sum.inl.inj heq
          subst i'
          exact (Finset.mem_erase.mp hi').1 rfl
      | inr j' => exact hadj.elim

/-- Target mass still present in a row after restricting to a list of
unprocessed table edges. -/
noncomputable def remainingTransportRow [Fintype β]
    (r : (α × β) → ENNReal) (remaining : List (α × β)) (i : α) : ENNReal :=
  ∑ j, if (i, j) ∈ remaining then r (i, j) else 0

/-- Target mass still present in a column after restricting to a list of
unprocessed table edges. -/
noncomputable def remainingTransportCol [Fintype α]
    (r : (α × β) → ENNReal) (remaining : List (α × β)) (j : β) : ENNReal :=
  ∑ i, if (i, j) ∈ remaining then r (i, j) else 0

/-- An edge is a leaf of the remaining positive support if all other target
mass in its remaining row vanishes, or all other target mass in its remaining
column vanishes. -/
def IsTransportLeafEdge
    (r : (α × β) → ENNReal) (edge : α × β)
    (remaining : List (α × β)) : Prop :=
  (∀ j, (edge.1, j) ∈ remaining → r (edge.1, j) = 0) ∨
    ∀ i, (i, edge.2) ∈ remaining → r (i, edge.2) = 0

/-- A list is a leaf-elimination order when each head is a leaf of the
positive support remaining in its tail. -/
def IsTransportLeafEliminationOrder
    (r : (α × β) → ENNReal) : List (α × β) → Prop
  | [] => True
  | edge :: remaining =>
      IsTransportLeafEdge r edge remaining ∧
        IsTransportLeafEliminationOrder r remaining

/-- An acyclic finite set of positive transport edges admits a
leaf-elimination listing of exactly those edges. -/
theorem exists_leafEliminationOrder_of_acyclic_edgeGraph
    [Fintype α] [Fintype β]
    (r : (α × β) → ENNReal) (edges : Finset (α × β))
    (hpositive : ∀ edge ∈ edges, r edge ≠ 0)
    (hacyclic : (transportEdgeGraph edges).IsAcyclic) :
    ∃ order : List (α × β),
      order.toFinset = edges ∧ order.Nodup ∧
        IsTransportLeafEliminationOrder r order := by
  classical
  refine Finset.strongInductionOn edges ?_ hpositive hacyclic
  intro current ih hcurrentPositive hcurrentAcyclic
  by_cases hcurrentEmpty : current = ∅
  · subst current
    exact ⟨[], by simp, List.nodup_nil, trivial⟩
  · have hnonempty : current.Nonempty := Finset.nonempty_iff_ne_empty.mpr hcurrentEmpty
    obtain ⟨edge, hedge, hleaf⟩ :=
      exists_mem_isTransportEdgeFinsetLeaf current hnonempty hcurrentAcyclic
    let remainingEdges := current.erase edge
    have hremainingSubset : remainingEdges ⊂ current :=
      Finset.erase_ssubset hedge
    have hremainingPositive :
        ∀ selected ∈ remainingEdges, r selected ≠ 0 := by
      intro selected hselected
      exact hcurrentPositive selected (Finset.mem_of_mem_erase hselected)
    have hremainingAcyclic :
        (transportEdgeGraph remainingEdges).IsAcyclic :=
      SimpleGraph.IsAcyclic.anti
        (transportEdgeGraph_mono (Finset.erase_subset edge current))
        hcurrentAcyclic
    obtain ⟨remaining, hremainingFinset, hremainingNodup, hremainingLeaf⟩ :=
      ih remainingEdges hremainingSubset hremainingPositive hremainingAcyclic
    have hedgeNotRemaining : edge ∉ remaining := by
      intro hmem
      have : edge ∈ remainingEdges := by
        rw [← hremainingFinset]
        exact List.mem_toFinset.mpr hmem
      exact (Finset.notMem_erase edge current) this
    have hleafList : IsTransportLeafEdge r edge remaining := by
      rcases hleaf with hrow | hcol
      · left
        intro j hj
        exfalso
        apply hrow j
        have hmem : (edge.1, j) ∈ remaining.toFinset :=
          List.mem_toFinset.mpr hj
        rw [hremainingFinset] at hmem
        simpa [remainingEdges] using hmem
      · right
        intro i hi
        exfalso
        apply hcol i
        have hmem : (i, edge.2) ∈ remaining.toFinset :=
          List.mem_toFinset.mpr hi
        rw [hremainingFinset] at hmem
        simpa [remainingEdges] using hmem
    refine ⟨edge :: remaining, ?_, ?_, ⟨hleafList, hremainingLeaf⟩⟩
    · simp only [List.toFinset_cons, hremainingFinset, remainingEdges]
      exact Finset.insert_erase hedge
    · exact List.nodup_cons.mpr ⟨hedgeNotRemaining, hremainingNodup⟩

omit [DecidableEq α] [DecidableEq β] in
/-- A list consisting entirely of zero target atoms is automatically a
leaf-elimination order. -/
theorem isTransportLeafEliminationOrder_of_forall_eq_zero
    (r : (α × β) → ENNReal) :
    ∀ order : List (α × β),
      (∀ edge ∈ order, r edge = 0) →
      IsTransportLeafEliminationOrder r order := by
  intro order hzero
  induction order with
  | nil => trivial
  | cons edge remaining ih =>
      constructor
      · left
        intro j hj
        exact hzero (edge.1, j) (List.mem_cons_of_mem edge hj)
      · exact ih fun selected hselected =>
          hzero selected (List.mem_cons_of_mem edge hselected)

omit [DecidableEq α] [DecidableEq β] in
/-- Appending only zero target atoms preserves a leaf-elimination order. -/
theorem IsTransportLeafEliminationOrder.append_zero
    {r : (α × β) → ENNReal} {order zeros : List (α × β)}
    (horder : IsTransportLeafEliminationOrder r order)
    (hzero : ∀ edge ∈ zeros, r edge = 0) :
    IsTransportLeafEliminationOrder r (order ++ zeros) := by
  induction order with
  | nil =>
      simpa using isTransportLeafEliminationOrder_of_forall_eq_zero r zeros hzero
  | cons edge remaining ih =>
      have hhead := horder.1
      have htail := horder.2
      constructor
      · rcases hhead with hrow | hcol
        · left
          intro j hj
          replace hj := List.mem_append.mp hj
          rcases hj with hj | hj
          · exact hrow j hj
          · exact hzero (edge.1, j) hj
        · right
          intro i hi
          replace hi := List.mem_append.mp hi
          rcases hi with hi | hi
          · exact hcol i hi
          · exact hzero (i, edge.2) hi
      · exact ih htail

/-- Finite positive support of an ENNReal transport table. -/
noncomputable def ennrealTransportSupportEdges [Fintype α] [Fintype β]
    (r : (α × β) → ENNReal) : Finset (α × β) :=
  Finset.univ.filter fun edge => r edge ≠ 0

omit [DecidableEq α] [DecidableEq β] in
/-- For a real table, the finite edge graph of its converted ENNReal support
is exactly its positive-support graph. -/
theorem transportEdgeGraph_realTransportPlanToENNReal_support
    [Fintype α] [Fintype β]
    (r : (α × β) → ℝ) :
    transportEdgeGraph
        (ennrealTransportSupportEdges (realTransportPlanToENNReal r)) =
      transportSupportGraph r := by
  ext u v
  cases u <;> cases v <;>
    simp [transportEdgeGraph, transportSupportGraph,
      ennrealTransportSupportEdges, realTransportPlanToENNReal,
      ENNReal.ofReal_eq_zero]

/-- An acyclic positive-support edge graph yields a complete duplicate-free
leaf-elimination order: eliminate positive forest edges first, then append all
zero table cells. -/
theorem exists_complete_leafEliminationOrder_of_acyclic
    [Fintype α] [Fintype β]
    (r : (α × β) → ENNReal)
    (hacyclic :
      (transportEdgeGraph (ennrealTransportSupportEdges r)).IsAcyclic) :
    ∃ order : List (α × β),
      IsCompleteEdgeOrder order ∧ order.Nodup ∧
        IsTransportLeafEliminationOrder r order := by
  classical
  let support := ennrealTransportSupportEdges r
  have hpositive : ∀ edge ∈ support, r edge ≠ 0 := by
    intro edge hedge
    exact (Finset.mem_filter.mp hedge).2
  obtain ⟨positiveOrder, hpositiveFinset, hpositiveNodup, hpositiveLeaf⟩ :=
    exists_leafEliminationOrder_of_acyclic_edgeGraph
      r support hpositive hacyclic
  let zeroEdges := (Finset.univ \ support).toList
  have hzero : ∀ edge ∈ zeroEdges, r edge = 0 := by
    intro edge hedge
    have hedge' : edge ∈ Finset.univ \ support := by
      simpa [zeroEdges] using hedge
    have hnotsupport := (Finset.mem_sdiff.mp hedge').2
    simp only [support, ennrealTransportSupportEdges,
      Finset.mem_filter, Finset.mem_univ, true_and] at hnotsupport
    exact not_ne_iff.mp hnotsupport
  let order := positiveOrder ++ zeroEdges
  have horderFinset : order.toFinset = Finset.univ := by
    simp only [order, List.toFinset_append, hpositiveFinset, zeroEdges,
      Finset.toList_toFinset]
    exact Finset.union_sdiff_of_subset (Finset.subset_univ support)
  refine ⟨order, ?_, ?_, hpositiveLeaf.append_zero hzero⟩
  · intro edge
    exact List.mem_toFinset.mp (horderFinset.symm ▸ Finset.mem_univ edge)
  · change (positiveOrder ++ zeroEdges).Nodup
    rw [List.nodup_append]
    have hzeroNodup : zeroEdges.Nodup := by
      dsimp [zeroEdges]
      exact (Finset.univ \ support).nodup_toList
    refine ⟨hpositiveNodup, hzeroNodup,
      fun positiveEdge hpositiveMem zeroEdge hzeroMem heq => ?_⟩
    subst zeroEdge
    have hedgeSupport : positiveEdge ∈ support := by
      rw [← hpositiveFinset]
      exact List.mem_toFinset.mpr hpositiveMem
    have hedgeComplement : positiveEdge ∈ Finset.univ \ support := by
      simpa [zeroEdges] using hzeroMem
    exact (Finset.mem_sdiff.mp hedgeComplement).2 hedgeSupport

/-- Remaining row mass splits into the head contribution and the tail mass
when the head edge is not repeated. -/
theorem remainingTransportRow_cons
    [Fintype β] (r : (α × β) → ENNReal) (edge : α × β)
    (remaining : List (α × β)) (hedge : edge ∉ remaining) (i : α) :
    remainingTransportRow r (edge :: remaining) i =
      (if i = edge.1 then r edge else 0) +
        remainingTransportRow r remaining i := by
  classical
  by_cases hi : i = edge.1
  · subst i
    unfold remainingTransportRow
    calc
      (∑ j, if (edge.1, j) ∈ edge :: remaining then r (edge.1, j) else 0) =
          ∑ j, ((if j = edge.2 then r edge else 0) +
            (if (edge.1, j) ∈ remaining then r (edge.1, j) else 0)) := by
        apply Finset.sum_congr rfl
        intro j hj
        by_cases hje : j = edge.2
        · subst j
          simp [hedge]
        · have hpair : (edge.1, j) ≠ edge :=
            fun h => hje (congrArg Prod.snd h)
          simp [hpair, hje]
      _ = r edge + ∑ j,
          if (edge.1, j) ∈ remaining then r (edge.1, j) else 0 := by
        rw [Finset.sum_add_distrib]
        simp
      _ = (if edge.1 = edge.1 then r edge else 0) +
          ∑ j, if (edge.1, j) ∈ remaining then r (edge.1, j) else 0 := by simp
  · simp only [remainingTransportRow, if_neg hi]
    rw [zero_add]
    apply Finset.sum_congr rfl
    intro j hj
    have hpair : (i, j) ≠ edge := fun h => hi (congrArg Prod.fst h)
    simp [hpair]

/-- Remaining column mass has the analogous head-tail decomposition. -/
theorem remainingTransportCol_cons
    [Fintype α] (r : (α × β) → ENNReal) (edge : α × β)
    (remaining : List (α × β)) (hedge : edge ∉ remaining) (j : β) :
    remainingTransportCol r (edge :: remaining) j =
      (if j = edge.2 then r edge else 0) +
        remainingTransportCol r remaining j := by
  classical
  by_cases hj : j = edge.2
  · subst j
    unfold remainingTransportCol
    calc
      (∑ i, if (i, edge.2) ∈ edge :: remaining then r (i, edge.2) else 0) =
          ∑ i, ((if i = edge.1 then r edge else 0) +
            (if (i, edge.2) ∈ remaining then r (i, edge.2) else 0)) := by
        apply Finset.sum_congr rfl
        intro i hi
        by_cases hie : i = edge.1
        · subst i
          simp [hedge]
        · have hpair : (i, edge.2) ≠ edge :=
            fun h => hie (congrArg Prod.fst h)
          simp [hpair, hie]
      _ = r edge + ∑ i,
          if (i, edge.2) ∈ remaining then r (i, edge.2) else 0 := by
        rw [Finset.sum_add_distrib]
        simp
      _ = (if edge.2 = edge.2 then r edge else 0) +
          ∑ i, if (i, edge.2) ∈ remaining then r (i, edge.2) else 0 := by simp
  · simp only [remainingTransportCol, if_neg hj]
    rw [zero_add]
    apply Finset.sum_congr rfl
    intro i hi
    have hpair : (i, j) ≠ edge := fun h => hj (congrArg Prod.snd h)
    simp [hpair]

/-- At a row-leaf edge, its remaining row mass is exactly its own target
mass. -/
theorem remainingTransportRow_cons_eq_of_leaf
    [Fintype β] (r : (α × β) → ENNReal) (edge : α × β)
    (remaining : List (α × β))
    (hrow : ∀ j, (edge.1, j) ∈ remaining → r (edge.1, j) = 0) :
    remainingTransportRow r (edge :: remaining) edge.1 = r edge := by
  classical
  unfold remainingTransportRow
  rw [Finset.sum_eq_single edge.2]
  · simp
  · intro j hj hne
    have hpair : (edge.1, j) ≠ edge :=
      fun h => hne (congrArg Prod.snd h)
    by_cases hmem : (edge.1, j) ∈ remaining
    · simp [hpair, hmem, hrow j hmem]
    · simp [hpair, hmem]
  · simp

/-- At a column-leaf edge, its remaining column mass is exactly its own
target mass. -/
theorem remainingTransportCol_cons_eq_of_leaf
    [Fintype α] (r : (α × β) → ENNReal) (edge : α × β)
    (remaining : List (α × β))
    (hcol : ∀ i, (i, edge.2) ∈ remaining → r (i, edge.2) = 0) :
    remainingTransportCol r (edge :: remaining) edge.2 = r edge := by
  classical
  unfold remainingTransportCol
  rw [Finset.sum_eq_single edge.1]
  · simp
  · intro i hi hne
    have hpair : (i, edge.2) ≠ edge :=
      fun h => hne (congrArg Prod.fst h)
    by_cases hmem : (i, edge.2) ∈ remaining
    · simp [hpair, hmem, hcol i hmem]
    · simp [hpair, hmem]
  · simp

/-- Every head edge contributes its target mass to the corresponding
remaining row. -/
theorem le_remainingTransportRow_cons
    [Fintype β] (r : (α × β) → ENNReal) (edge : α × β)
    (remaining : List (α × β)) :
    r edge ≤ remainingTransportRow r (edge :: remaining) edge.1 := by
  classical
  unfold remainingTransportRow
  calc
    r edge = if (edge.1, edge.2) ∈ edge :: remaining then
        r (edge.1, edge.2) else 0 := by simp
    _ ≤ ∑ j, if (edge.1, j) ∈ edge :: remaining then r (edge.1, j) else 0 :=
      Finset.single_le_sum
        (s := Finset.univ)
        (f := fun j => if (edge.1, j) ∈ edge :: remaining then
          r (edge.1, j) else 0)
        (fun _ _ => bot_le) (Finset.mem_univ edge.2)

/-- Every head edge contributes its target mass to the corresponding
remaining column. -/
theorem le_remainingTransportCol_cons
    [Fintype α] (r : (α × β) → ENNReal) (edge : α × β)
    (remaining : List (α × β)) :
    r edge ≤ remainingTransportCol r (edge :: remaining) edge.2 := by
  classical
  unfold remainingTransportCol
  calc
    r edge = if (edge.1, edge.2) ∈ edge :: remaining then
        r (edge.1, edge.2) else 0 := by simp
    _ ≤ ∑ i, if (i, edge.2) ∈ edge :: remaining then r (i, edge.2) else 0 :=
      Finset.single_le_sum
        (s := Finset.univ)
        (f := fun i => if (i, edge.2) ∈ edge :: remaining then
          r (i, edge.2) else 0)
        (fun _ _ => bot_le) (Finset.mem_univ edge.1)

/-- Greedy allocation from the target remaining row and column sums equals
the target edge mass whenever the edge is a support leaf. -/
theorem greedyTransportAllocation_eq_of_leaf
    [Fintype α] [Fintype β]
    (r : (α × β) → ENNReal) (edge : α × β)
    (remaining : List (α × β))
    (hleaf : IsTransportLeafEdge r edge remaining)
    (mass : (α × β) → ENNReal) :
    greedyTransportAllocation
      (remainingTransportRow r (edge :: remaining),
        remainingTransportCol r (edge :: remaining), mass) edge = r edge := by
  rcases hleaf with hrow | hcol
  · change min (remainingTransportRow r (edge :: remaining) edge.1)
      (remainingTransportCol r (edge :: remaining) edge.2) = r edge
    rw [remainingTransportRow_cons_eq_of_leaf _ _ _ hrow]
    exact min_eq_left (le_remainingTransportCol_cons r edge remaining)
  · change min (remainingTransportRow r (edge :: remaining) edge.1)
      (remainingTransportCol r (edge :: remaining) edge.2) = r edge
    rw [remainingTransportCol_cons_eq_of_leaf _ _ _ hcol]
    exact min_eq_right (le_remainingTransportRow_cons r edge remaining)

/-- Target mass already assigned on a processed edge prefix. -/
def processedTransportMass
    (r : (α × β) → ENNReal) (processed : List (α × β)) :
    (α × β) → ENNReal :=
  fun edge => if edge ∈ processed then r edge else 0

/-- The exact greedy state expected after `processed` and before
`remaining`. -/
noncomputable def targetGreedyTransportState
    [Fintype α] [Fintype β]
    (r : (α × β) → ENNReal)
    (processed remaining : List (α × β)) : GreedyTransportState α β :=
  (remainingTransportRow r remaining,
    remainingTransportCol r remaining,
    processedTransportMass r processed)

/-- One greedy update advances the exact target state across a leaf edge. -/
theorem greedyTransportStep_targetState
    [Fintype α] [Fintype β]
    (r : (α × β) → ENNReal) (processed : List (α × β))
    (edge : α × β) (remaining : List (α × β))
    (hrfinite : ∀ selected, r selected ≠ ∞)
    (hprocessed : edge ∉ processed) (hremaining : edge ∉ remaining)
    (hleaf : IsTransportLeafEdge r edge remaining) :
    greedyTransportStep
        (targetGreedyTransportState r processed (edge :: remaining)) edge =
      targetGreedyTransportState r (processed ++ [edge]) remaining := by
  classical
  have hamount :
      greedyTransportAllocation
        (targetGreedyTransportState r processed (edge :: remaining)) edge = r edge := by
    exact greedyTransportAllocation_eq_of_leaf r edge remaining hleaf
      (processedTransportMass r processed)
  apply Prod.ext
  · funext i
    unfold greedyTransportStep
    simp only [hamount]
    unfold targetGreedyTransportState
    by_cases hi : i = edge.1
    · subst i
      simp only [Function.update_self]
      rw [remainingTransportRow_cons r edge remaining hremaining]
      simp only [if_true]
      exact ENNReal.add_sub_cancel_left (hrfinite edge)
    · simp only [Function.update_of_ne hi]
      rw [remainingTransportRow_cons r edge remaining hremaining]
      simp [hi]
  · apply Prod.ext
    · funext j
      unfold greedyTransportStep
      simp only [hamount]
      unfold targetGreedyTransportState
      by_cases hj : j = edge.2
      · subst j
        simp only [Function.update_self]
        rw [remainingTransportCol_cons r edge remaining hremaining]
        simp only [if_true]
        exact ENNReal.add_sub_cancel_left (hrfinite edge)
      · simp only [Function.update_of_ne hj]
        rw [remainingTransportCol_cons r edge remaining hremaining]
        simp [hj]
    · funext selected
      unfold greedyTransportStep
      simp only [hamount]
      unfold targetGreedyTransportState processedTransportMass
      by_cases hs : selected = edge
      · subst selected
        simp [hprocessed]
      · simp [hs]

/-- Following a leaf-elimination order advances the exact target state from
the processed prefix to the empty remainder. -/
theorem foldl_greedyTransportStep_targetState
    [Fintype α] [Fintype β]
    (r : (α × β) → ENNReal) (hrfinite : ∀ edge, r edge ≠ ∞) :
    ∀ (processed order : List (α × β)),
      (∀ edge, edge ∈ order → edge ∉ processed) →
      order.Nodup →
      IsTransportLeafEliminationOrder r order →
      order.foldl greedyTransportStep
          (targetGreedyTransportState r processed order) =
        targetGreedyTransportState r (processed ++ order) [] := by
  intro processed order hdisjoint hnodup hleaf
  induction order generalizing processed with
  | nil => simp
  | cons edge remaining ih =>
      have hremaining : edge ∉ remaining := List.nodup_cons.mp hnodup |>.1
      have hremainingNodup : remaining.Nodup := List.nodup_cons.mp hnodup |>.2
      have hprocessed : edge ∉ processed :=
        hdisjoint edge (List.mem_cons_self)
      have hleafHead : IsTransportLeafEdge r edge remaining := hleaf.1
      have hleafTail : IsTransportLeafEliminationOrder r remaining := hleaf.2
      have hdisjointTail :
          ∀ selected, selected ∈ remaining →
            selected ∉ processed ++ [edge] := by
        intro selected hselected
        simp only [List.mem_append, List.mem_singleton, not_or]
        exact ⟨hdisjoint selected (List.mem_cons_of_mem edge hselected),
          fun h => hremaining (h ▸ hselected)⟩
      simp only [List.foldl_cons]
      rw [greedyTransportStep_targetState r processed edge remaining
        hrfinite hprocessed hremaining hleafHead]
      rw [ih (processed ++ [edge]) hdisjointTail hremainingNodup hleafTail]
      have happend : (processed ++ [edge]) ++ remaining =
          processed ++ edge :: remaining := by simp
      rw [happend]

/-- A complete edge list retains every target atom in each initial remaining
row sum. -/
theorem remainingTransportRow_eq_sum_of_complete
    [Fintype β] (r : (α × β) → ENNReal) (order : List (α × β))
    (hcomplete : IsCompleteEdgeOrder order) (i : α) :
    remainingTransportRow r order i = ∑ j, r (i, j) := by
  classical
  unfold remainingTransportRow
  apply Finset.sum_congr rfl
  intro j hj
  rw [if_pos (hcomplete (i, j))]

/-- The analogous identity holds for initial remaining column sums. -/
theorem remainingTransportCol_eq_sum_of_complete
    [Fintype α] (r : (α × β) → ENNReal) (order : List (α × β))
    (hcomplete : IsCompleteEdgeOrder order) (j : β) :
    remainingTransportCol r order j = ∑ i, r (i, j) := by
  classical
  unfold remainingTransportCol
  apply Finset.sum_congr rfl
  intro i hi
  rw [if_pos (hcomplete (i, j))]

/-- A complete duplicate-free leaf-elimination order makes the greedy
algorithm reproduce the prescribed finite target mass table exactly. -/
theorem greedyTransportMass_eq_of_leafEliminationOrder
    [Fintype α] [Fintype β]
    (p : α → ENNReal) (q : β → ENNReal) (r : (α × β) → ENNReal)
    (hrow : ∀ i, ∑ j, r (i, j) = p i)
    (hcol : ∀ j, ∑ i, r (i, j) = q j)
    (hrfinite : ∀ edge, r edge ≠ ∞)
    (order : List (α × β)) (hcomplete : IsCompleteEdgeOrder order)
    (hnodup : order.Nodup)
    (hleaf : IsTransportLeafEliminationOrder r order) :
    greedyTransportMass p q order = r := by
  classical
  have hinitial : targetGreedyTransportState r [] order =
      initialGreedyTransportState p q := by
    apply Prod.ext
    · funext i
      change remainingTransportRow r order i = p i
      rw [remainingTransportRow_eq_sum_of_complete r order hcomplete i,
        hrow i]
    · apply Prod.ext
      · funext j
        change remainingTransportCol r order j = q j
        rw [remainingTransportCol_eq_sum_of_complete r order hcomplete j,
          hcol j]
      · funext edge
        change processedTransportMass r [] edge = 0
        simp [processedTransportMass]
  have hfold := foldl_greedyTransportStep_targetState r hrfinite [] order
    (fun edge hedge => by simp) hnodup hleaf
  unfold greedyTransportMass greedyTransportState
  rw [← hinitial, hfold]
  funext edge
  simp [targetGreedyTransportState, processedTransportMass, hcomplete edge]

/-- Specialization to a feasible PMF transport table; finiteness of every
atom follows automatically from its row marginal. -/
theorem greedyTransportMass_eq_transportPlan_of_leafEliminationOrder
    [Fintype α] [Fintype β]
    (p : PMF α) (q : PMF β) (r : (α × β) → ENNReal)
    (hr : r ∈ transportPlans p q)
    (order : List (α × β)) (hcomplete : IsCompleteEdgeOrder order)
    (hnodup : order.Nodup)
    (hleaf : IsTransportLeafEliminationOrder r order) :
    greedyTransportMass p q order = r := by
  apply greedyTransportMass_eq_of_leafEliminationOrder p q r
    hr.1 hr.2
  · intro edge
    apply ne_of_lt
    calc
      r edge ≤ ∑ j, r (edge.1, j) :=
        Finset.single_le_sum
          (f := fun j => r (edge.1, j))
          (fun _ _ => bot_le) (Finset.mem_univ edge.2)
      _ = p edge.1 := hr.1 edge.1
      _ < ∞ := p.apply_lt_top edge.1
  · exact hcomplete
  · exact hnodup
  · exact hleaf

/-- A complete duplicate-free edge list determines an element of the finite
candidate order type. -/
noncomputable def completeEdgeOrderOfList
    [Fintype α] [Fintype β]
    (order : List (α × β)) (hcomplete : IsCompleteEdgeOrder order)
    (hnodup : order.Nodup) : CompleteEdgeOrder (α := α) (β := β) := by
  refine ⟨order, List.mem_permutations.mpr ?_⟩
  apply (List.perm_ext_iff_of_nodup hnodup
    (Finset.univ : Finset (α × β)).nodup_toList).mpr
  intro edge
  constructor
  · intro hedge
    simp
  · intro hedge
    exact hcomplete edge

/-- A leaf-elimination list therefore identifies a finite greedy candidate
whose PMF is exactly the prescribed feasible transport plan. -/
theorem completeOrderTransportCoupling_completeEdgeOrderOfList_eq
    [Fintype α] [Fintype β]
    (p : PMF α) (q : PMF β) (r : (α × β) → ENNReal)
    (hr : r ∈ transportPlans p q)
    (order : List (α × β)) (hcomplete : IsCompleteEdgeOrder order)
    (hnodup : order.Nodup)
    (hleaf : IsTransportLeafEliminationOrder r order) :
    completeOrderTransportCoupling p q
        (completeEdgeOrderOfList order hcomplete hnodup) =
      transportPlanPMF p q r hr := by
  apply PMF.ext
  intro edge
  rw [transportPlanPMF_apply]
  change greedyTransportMass p q order edge = r edge
  exact congrFun
    (greedyTransportMass_eq_transportPlan_of_leafEliminationOrder
      p q r hr order hcomplete hnodup hleaf) edge

/-- An acyclic feasible real transport plan is represented exactly by one of
the finite complete-order greedy candidates. -/
theorem exists_completeOrderTransportCoupling_eq_of_realSupport_acyclic
    [Fintype α] [Fintype β]
    (p : PMF α) (q : PMF β) (r : (α × β) → ℝ)
    (hr : r ∈ realTransportPlans p q)
    (hacyclic : (transportSupportGraph r).IsAcyclic) :
    ∃ order : CompleteEdgeOrder (α := α) (β := β),
      completeOrderTransportCoupling p q order =
        transportPlanPMF p q (realTransportPlanToENNReal r)
          (realTransportPlanToENNReal_mem_transportPlans hr) := by
  have hconvertedAcyclic :
      (transportEdgeGraph
        (ennrealTransportSupportEdges
          (realTransportPlanToENNReal r))).IsAcyclic := by
    rw [transportEdgeGraph_realTransportPlanToENNReal_support r]
    exact hacyclic
  obtain ⟨edgeOrder, hcomplete, hnodup, hleaf⟩ :=
    exists_complete_leafEliminationOrder_of_acyclic
      (realTransportPlanToENNReal r) hconvertedAcyclic
  let order := completeEdgeOrderOfList edgeOrder hcomplete hnodup
  refine ⟨order, ?_⟩
  exact completeOrderTransportCoupling_completeEdgeOrderOfList_eq
    p q (realTransportPlanToENNReal r)
    (realTransportPlanToENNReal_mem_transportPlans hr)
    edgeOrder hcomplete hnodup hleaf

/-- On finite spaces, the complete-order greedy candidate family contains an
optimal transport coupling. -/
theorem greedyTransportCandidatesComplete
    [Fintype α] [Fintype β]
    (p : PMF α) (q : PMF β) (cost : α → β → NNReal) :
    GreedyTransportCandidatesComplete p q cost := by
  intro joint hjoint
  let s : (α × β) → ENNReal := fun edge => joint edge
  have hs : s ∈ transportPlans p q :=
    IsPMFCoupling.mem_transportPlans p q joint hjoint
  obtain ⟨r, hr, hmin, hacyclic⟩ :=
    exists_realTransportCost_minimizer_support_acyclic p q cost
  obtain ⟨order, horder⟩ :=
    exists_completeOrderTransportCoupling_eq_of_realSupport_acyclic
      p q r hr hacyclic
  refine ⟨order, ?_⟩
  rw [horder]
  have hreal := hmin (transportPlanToReal s)
    (transportPlanToReal_mem_realTransportPlans hs)
  have hofReal := ENNReal.ofReal_le_ofReal hreal
  rw [← transportCost_realTransportPlanToENNReal cost hr.1,
    realTransportCost_transportPlanToReal cost hs,
    ENNReal.ofReal_toReal (transportCost_ne_top cost hs)] at hofReal
  change transportCost cost (realTransportPlanToENNReal r) ≤
    transportCost cost s
  exact hofReal

end Mcmc.Finite
