using VerifiedSamplers

const Backends = VerifiedSamplers.Backends

mark(value::Bool) = value ? "yes" : "—"

function render_backend_registry()
    lines = [
        "# Julia backend registry",
        "",
        "<!-- Generated by VerifiedSamplers.jl/tools/generate_backend_docs.jl; do not edit manually. -->",
        "",
        "Capabilities describe executable support, not mathematical proof strength. Numerical certificates remain optional, independent evidence.",
        "",
        "| Backend | Execution class | Evidence | Scalar | Vector | Deterministic trace | Independent chains | Within-chain parallel | Accelerator | Note |",
        "|---|---|---|---:|---:|---:|---:|---:|---:|---|",
    ]
    for backend in Backends.backend_registry()
        capabilities = backend.capabilities
        row = join([
            "`$(backend.name)`",
            "`$(backend.execution)`",
            "`$(backend.evidence)`",
            mark(capabilities.scalar),
            mark(capabilities.vector),
            mark(capabilities.deterministic_trace),
            mark(capabilities.independent_chains),
            mark(capabilities.within_chain_parallelism),
            mark(capabilities.accelerator),
            replace(backend.note, "|" => "\\|"),
        ], " | ")
        push!(lines, "| $row |")
    end
    append!(lines, [
        "",
        "## Batched backend protocol",
        "",
        "`HostBatchBackend` is the maintained ordinary-array implementation. `AcceleratorBatchBackend` is a fail-closed adapter contract: an extension supplies its launcher and operation set, and begins at `DocumentedBoundary` unless stronger evidence is recorded. External adapters are intentionally absent from the maintained registry.",
        "",
        "`broadcast_accelerator` is the scoped maintained operation: Gaussian RWMH over broadcast-compatible arrays with explicit Gaussian and uniform events. `Tested` refers to host-array conformance with scalar Reference, not a claim about any particular GPU runtime.",
        "",
        "Independent-chain execution owns one explicit seed per state. Device transfer, RNG realization, reductions, callback support, and floating-point behavior remain obligations of each accelerator adapter.",
    ])
    join(lines, '\n') * "\n"
end

function main(args)
    length(args) == 1 || error("usage: generate_backend_docs.jl OUTPUT")
    write(only(args), render_backend_registry())
end

main(ARGS)
