using VerifiedSamplers

const Reference = VerifiedSamplers.Reference

render_names(names) = isempty(names) ? "—" :
    join(("`$name`" for name in names), "<br>")

function render_artifact_registry()
    facets = Reference.artifact_facets()
    rows = [
        ("Programs", facets.programs),
        ("Restricted targets", facets.targets),
        ("Composable schedules", facets.schedules),
        ("Transforms", facets.transforms),
        ("Dynamic-tree descriptors", facets.dynamic_trees),
        ("NUTS tree programs", facets.nuts_tree_programs),
    ]
    lines = [
        "# Reference artifact registry",
        "",
        "<!-- Generated by VerifiedSamplers.jl/tools/generate_artifact_docs.jl; do not edit manually. -->",
        "",
        "This page lists every top-level declaration decoded from canonical IR format version $(Reference.IR_FORMAT_VERSION). Presence records executable presentation, not a kernel theorem or floating-point refinement claim.",
        "",
        "| Facet | Count | Declarations |",
        "|---|---:|---|",
    ]
    for (label, names) in rows
        push!(lines, "| $label | $(length(names)) | $(render_names(names)) |")
    end
    join(lines, '\n') * "\n"
end

function main(args)
    length(args) == 1 || error("usage: generate_artifact_docs.jl OUTPUT")
    write(only(args), render_artifact_registry())
end

main(ARGS)
